version: "3.7"

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6381:6379"
    networks:
      - app-tier3

  db:
    image: mariadb
    container_name: maria
    restart: unless-stopped
    command: --max_allowed_packet=1024M
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'Aa123456!'

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:

      - elastic

  blog-api:
    image: natanm/blog-api:0.0.3  
    restart: unless-stopped
    ports:
      - 3000:3000 


volumes:
  data01:
    driver: local
  mariadb:

networks:
  elastic:
    driver: bridge
  app-tier:
    driver: bridge
  app-tier3:
    driver: overlay
    driver_opts:
      encrypted: "true"
    internal: false
    
    
